name: MagicBlock
version: '3.0.4'
main: io.github.syferie.magicblock.MagicBlockPlugin
api-version: '1.19'
authors: [Syferie]
description: A plugin that allows players to use magic blocks with limited uses.
softdepend: [PlaceholderAPI]

commands:
  magicblock:
    description: MagicBlock main command
    aliases: [mb]
    usage: /<command> [args]

permissions:
  magicblock.admin:
    description: Allows access to all MagicBlock commands
    default: op
    children:
      magicblock.use: true
      magicblock.give: true
      magicblock.reload: true
      magicblock.settimes: true
      magicblock.addtimes: true
      magicblock.food: true
  magicblock.use:
    description: Allows basic usage of MagicBlock
    default: true
  magicblock.give:
    description: Allows giving MagicBlocks to other players
    default: op
  magicblock.reload:
    description: Allows reloading the plugin configuration
    default: op
  magicblock.settimes:
    description: Allows setting use times for MagicBlocks
    default: op
  magicblock.addtimes:
    description: Allows adding use times to MagicBlocks
    default: op
  magicblock.food:
    description: Allows using magic food items
    default: true